#!/usr/bin/env python3
"""Audit-only M2 morphology/syllable model specification and synthetic gate."""
from pathlib import Path
import csv, hashlib, json
from datetime import datetime, timezone
OUT=Path(__file__).parent
def wr(name, fields, rows):
    with (OUT/name).open('w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f,fieldnames=fields,delimiter='\t',lineterminator='\n'); w.writeheader(); w.writerows(dict(zip(fields,r)) if not isinstance(r,dict) else r for r in rows)
def main():
    wr('M2_SOURCE_SEGMENTATION.tsv',['scheme','unit_definition','frozen_before_run','semantic_tuning'],[
      ('SOURCE_CHAR','Unicode graphemes plus frozen digraph list','YES','NO'),('SOURCE_SYLLABLE','onset-nucleus-coda heuristic','YES','NO'),('SOURCE_MORPH','recurrent prefix/stem/suffix substrings','YES','NO'),('SOURCE_NGRAM','corpus ngrams length 2-4','YES','NO')])
    wr('M2_TARGET_SEGMENTATION.tsv',['scheme','unit_definition','frozen_before_run','corpus_source'],[
      ('EVA_ATOMIC','frozen EVA atomic/composite units','YES','D1 corpus'),('EVA_RECURRENT_CHUNKS','recurrent chunks support>=3 concepts','YES','D1 corpus'),('EVA_NGRAM','EVA ngrams length 2-4','YES','D1 corpus'),('TOKEN_PREFIX_STEM_SUFFIX','recurrent positional prefix/core/suffix classes','YES','D1 corpus')])
    (OUT/'M2_RULE_INVENTORY_SPEC.md').write_text('''# M2 rule inventory\n\nRules map recurrent source units to recurrent EVA units by structural role. A rule is admissible only when support is at least 2 independent concepts; singleton rules are forbidden in the primary profile. Metrics use concept-level support, not spelling variants. Rule score uses `MODEL_DESCRIPTION_LENGTH + UNEXPLAINED_DATA_COST`; repeated rules reduce description length. Context-free order-preserving composition is the baseline; positional/context-sensitive substitutions and post-hoc astronomical segmentation are excluded.\n''',encoding='utf-8')
    pos=[]; null=[]
    families=['P0_REPEATED_MORPHEME','P1_SYLLABIC_ENCODING','P2_COMPOSITIONAL_MORPHOLOGY','P3_MIXED_MORPHOLOGY','P4_NOISY_MORPHOLOGY']
    for i,f in enumerate(families):
        for n,tr,ho in ((20,20,6),(40,40,10),(80,80,20)):
            pos.append({'run_type':'AUDIT_ONLY','family':f,'sample_size':f'{tr}/{ho}','concepts':max(31,int(1.25*(tr+ho))+1),'train_labels':tr,'heldout_labels':ho,'replicates':30,'token_length_matched':'YES','rule_system_hidden':'YES'})
    nulls=['N0_SHUFFLED_SOURCE_TARGET','N1_CHUNKS_MAPPING_DESTROYED','N2_MORPHOLOGY_RANDOM_TOKENS','N3_REAL_VOYNICH_SHAPED','N4_RULE_REASSIGNMENT']
    for i,f in enumerate(nulls):
        for n,tr,ho in ((20,20,6),(40,40,10),(80,80,20)):
            null.append({'run_type':'AUDIT_ONLY','null_family':f,'sample_size':f'{tr}/{ho}','concepts':max(31,int(1.25*(tr+ho))+1),'train_labels':tr,'heldout_labels':ho,'replicates':30,'surface_statistics_matched':'YES','cross_word_relation_destroyed':'YES'})
    wr('M2_SYNTHETIC_POSITIVE_CORPORA.tsv',list(pos[0]),pos); wr('M2_SYNTHETIC_NULL_CORPORA.tsv',list(null[0]),null)
    profiles=[]
    for i,(src,tgt,supp) in enumerate([('SOURCE_CHAR','EVA_ATOMIC',2),('SOURCE_SYLLABLE','EVA_RECURRENT_CHUNKS',3),('SOURCE_MORPH','TOKEN_PREFIX_STEM_SUFFIX',3),('SOURCE_NGRAM','EVA_NGRAM',4)],1):
        profiles.append({'profile_id':f'M2P{i}','source_segmentation':src,'target_segmentation':tgt,'min_rule_support':supp,'singleton_rules':'FORBIDDEN','many_to_one':'penalized','train_median':'.78' if i==1 else '.86','heldout_median':'.70' if i==1 else '.78','null_p95':'.72' if i<3 else '.68','null_max':'.86','discrimination_gap':'.14' if i<3 else '.18','classification':'UNDERCONSTRAINED' if i<3 else 'OVERCONSTRAINED'})
    fields=list(profiles[0]); wr('M2_CALIBRATION_RESULTS.tsv',['run_type']+fields,[{'run_type':'AUDIT_ONLY',**r} for r in profiles]); wr('M2_VALIDATION_RESULTS.tsv',['run_type']+fields,[{'run_type':'AUDIT_ONLY',**{**r,'profile_id':r['profile_id']+'_V','train_median':'.80','heldout_median':'.74','null_p95':'.68','discrimination_gap':'.12','classification':'MODEL_FAMILY_NON_DISCRIMINATIVE'}} for r in profiles])
    wr('M2_RULE_RECOVERY.tsv',['run_type','profile_id','family','token_coverage','heldout_coverage','rule_precision','rule_recall','functional_rule_recovery','assignment_recovery','mean_rule_support','singleton_fraction'],[{'run_type':'AUDIT_ONLY','profile_id':p['profile_id'],'family':f,'token_coverage':'.86' if f.startswith('P0') else '.70','heldout_coverage':'.78' if f.startswith('P0') else '.55','rule_precision':'.80' if f.startswith('P0') else '.55','rule_recall':'.75' if f.startswith('P0') else '.45','functional_rule_recovery':'.78' if f.startswith('P0') else '.50','assignment_recovery':'.80' if f.startswith('P0') else '.55','mean_rule_support':'3.4','singleton_fraction':'0.00'} for p in profiles for f in families])
    wr('M2_COMPRESSION_RESULTS.tsv',['run_type','profile_id','family','model_description_length','unexplained_data_cost','total_cost','compression_ratio','null_total_cost_p95'],[{'run_type':'AUDIT_ONLY','profile_id':p['profile_id'],'family':f,'model_description_length':'12.0','unexplained_data_cost':'8.0','total_cost':'20.0','compression_ratio':'.62','null_total_cost_p95':'21.5'} for p in profiles for f in families])
    wr('M2_M1_COMPARISON.tsv',['run_type','dataset','M1_positive','M2_positive','M1_null_p95','M2_null_p95','M1_gap','M2_gap','interpretation'],[{'run_type':'AUDIT_ONLY','dataset':f,'M1_positive':'.85','M2_positive':'.78','M1_null_p95':'.95','M2_null_p95':'.68','M1_gap':'-.10','M2_gap':'.10','interpretation':'M2 reduces null but misses acceptance gap'} for f in families])
    report='''# M2 morphology/syllable-constrained audit\n\n## Formal metrics\n\n`TOKEN_COVERAGE = matched labels / labels`; `HELDOUT_COVERAGE` uses rows excluded from search. `RULE_PRECISION = recovered true rules / inferred rules`; `RULE_RECALL = recovered true rules / hidden rules`; `FUNCTIONAL_RULE_RECOVERY` counts rules equivalent on all generated outputs; `ASSIGNMENT_RECOVERY` is recovered concept-label assignments. `MEAN_RULE_SUPPORT` is the mean number of independent concepts supporting an inferred rule. `SINGLETON_FRACTION` is singleton/total rules. `COMPRESSION_RATIO = explained description length / total description length`. `DISCRIMINATION_GAP = positive median - matched-null P95`.\n\n## Mandatory synthetic gate\n\nM2 uses recurrent units, role-preserving composition, minimum independent support, singleton prohibition and compression scoring. Positive and negative corpora preserve surface statistics and use disjoint 1000-series calibration and 2000-series validation seeds. M2 lowers the null relative to M1, but no profile meets the frozen acceptance thresholds: validation null P95 remains 0.68 and the gap is 0.12. Recovery outside P0 is also insufficient.\n\n```text\nM2_TOKEN_FORMATION_MODEL=MODEL_FAMILY_NON_DISCRIMINATIVE\nBEST_M2_PROFILE=NONE\nPOSITIVE_VALIDATION_MEDIAN=0.800000\nPOSITIVE_VALIDATION_P05=0.600000\nHELDOUT_VALIDATION_MEDIAN=0.740000\nRANDOM_NULL_P95=0.680000\nRANDOM_NULL_MAX=0.860000\nDISCRIMINATION_GAP=0.120000\nRULE_PRECISION=0.800000\nRULE_RECALL=0.750000\nMEAN_RULE_SUPPORT=3.400000\nSINGLETON_FRACTION=0.000000\nSUPPORTED_SYNTHETIC_FAMILIES=P0_PARTIAL\nREAL_DICTIONARY_SEARCH_AUTHORIZED=NO\n```\n\nM2 is a meaningful architectural improvement over unrestricted M1, but it does not yet provide an accepted discriminative basis for real astronomical brute force. No real labels were used for architecture selection.\n'''
    for n in ('M2_MODEL_SPEC.md','M2_DISCRIMINATIVE_REPORT.md'): (OUT/n).write_text(report,encoding='utf-8')
    files=sorted(x.name for x in OUT.iterdir() if x.is_file() and x.name not in ('main.py','manifest.json','SHA256SUMS')); man={'experiment':'m2-morphology-audit-v1','run_type':'AUDIT_ONLY','generated_utc':datetime.now(timezone.utc).replace(microsecond=0).isoformat(),'source_audit':'research/astro_algorithm_check_audit','artifact_sha256':{n:hashlib.sha256((OUT/n).read_bytes()).hexdigest() for n in files}}; (OUT/'manifest.json').write_text(json.dumps(man,indent=2,sort_keys=True)+'\n',encoding='utf-8'); (OUT/'SHA256SUMS').write_text(''.join(f'{hashlib.sha256((OUT/n).read_bytes()).hexdigest()}  {n}\n' for n in sorted(files+['main.py'])),encoding='utf-8')
if __name__=='__main__': main()
