package mnemonicspace

func FrozenRegistry() []MechanismSpec {
	latin23 := "ABCDEFGHIKLMNOPQRSTVXYZ"
	f01CoreParams := ParameterSet{
		ID:          "f01-core-bounded",
		Origin:      OriginHistoricalBounded,
		Frozen:      true,
		Description: "Deterministic bounded F01 core parameters for validation runs.",
		F01:         &F01Parameters{NumRings: 12, Alphabet: latin23, ReadRadius: 5, Order: "INNER_TO_OUTER"},
	}
	f01ProfileParams := ParameterSet{
		ID:          "f01-profile-latin23-r12",
		Origin:      OriginHistoricalFrozen,
		Frozen:      true,
		Description: "Task80 frozen Latin23/R12 profile.",
		F01:         &F01Parameters{NumRings: 12, Alphabet: latin23, ReadRadius: 5, Order: "INNER_TO_OUTER"},
	}
	f08Params := ParameterSet{
		ID:          "f08-centre-edge-small",
		Origin:      OriginGenericGrid,
		Frozen:      true,
		Description: "Small deterministic positional grid.",
		F08:         &F08Parameters{Capacity: 10, Start: 0, Direction: "FORWARD", EmptyMarker: "?", Alphabet: latin23},
	}
	f11Params := ParameterSet{
		ID:          "f11-core-default",
		Origin:      OriginHistoricalFrozen,
		Frozen:      true,
		Description: "Core indexed cue lookup without frozen cue semantics.",
		F11:         &F11Parameters{},
	}
	f12Params := ParameterSet{
		ID:          "f12-cycle-default",
		Origin:      OriginGenericGrid,
		Frozen:      true,
		Description: "Deterministic small temporal cue cycle.",
		F12:         &F12Parameters{Period: 4, InitialTick: 0, AdvanceSteps: 1},
	}
	rotationParams := ParameterSet{
		ID:          "rotation-index-small",
		Origin:      OriginControlOnly,
		Frozen:      true,
		Description: "Minimal counterfactual rotation plus indexing boundary case.",
		Rotation:    &RotationIndexParameters{Offset: 1},
	}
	storageParams := ParameterSet{
		ID:          "storage-associate-small",
		Origin:      OriginControlOnly,
		Frozen:      true,
		Description: "Minimal explicit storage plus association boundary case.",
		Storage:     &StorageAssociateParameters{Capacity: 4},
	}

	return []MechanismSpec{
		{
			ID:                    "f01_speculum_core",
			Version:               "v1",
			Family:                FamilyF01,
			Status:                StatusFExact,
			Provenance:            []string{"FONTANA_MODELS_FROZEN_V1", "FONTANA_OPERATION_ALGEBRA_V1"},
			SourceModels:          []string{"F01_SPECULUM_CORE"},
			Encoding:              []OperationInvocation{{Operation: "rotate", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}, {"orientation", TypeOrientation}}, Outputs: []DomainValue{{"state", TypeExternalState}}, Note: "iterated per symbol position"}},
			Retrieval:             []OperationInvocation{{Operation: "align", Inputs: []DomainValue{{"state", TypeExternalState}, {"alignment", TypeAlignment}}, Outputs: []DomainValue{{"obs", TypeObservation}}}, {Operation: "traverse", Inputs: []DomainValue{{"state", TypeExternalState}, {"path", TypePath}}, Outputs: []DomainValue{{"seq", TypeSymbolSequence}}}, {Operation: "compose", Inputs: []DomainValue{{"seq", TypeSymbolSequence}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			StateSchema:           "independent ring orientations only",
			InputSchema:           "SymbolSequence",
			Initialization:        "all unused rings receive deterministic filler offsets from seed",
			TransitionRules:       []string{"each symbol rotates exactly one ring", "unused rings remain observable but semantically inert"},
			ObservationRule:       "serialize visible letters at the marked radius in physical ring order",
			Serialization:         ObservableContract{SymbolSource: "visible letters at marked radius", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalExactWithConvention, SupportsContext: true, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage, CarrierConvention}, Retrieve: []Carrier{CarrierExternalState, CarrierConvention, CarrierContext}},
			ExpectedReversibility: "exact with convention only",
			AmbiguitySemantics:    "without convention, multiple prefixes/orders remain compatible",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption, ErrorConventionCorrupt},
			Parameters:            []ParameterSet{f01CoreParams},
			SurfaceRole:           SurfaceLiteralSequence,
			runtime:               kindF01,
		},
		{
			ID:                    "f01_speculum_profile_latin23_r12",
			Version:               "v1",
			Family:                FamilyF01,
			Status:                StatusFProfile,
			Provenance:            []string{"FONTANA_MODELS_FROZEN_V1", "FONTANA_OPERATION_ALGEBRA_V1"},
			SourceModels:          []string{"F01_SPECULUM_PROFILE_LATIN23_R12"},
			Encoding:              []OperationInvocation{{Operation: "rotate", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}, {"orientation", TypeOrientation}}, Outputs: []DomainValue{{"state", TypeExternalState}}, Note: "iterated per symbol position"}},
			Retrieval:             []OperationInvocation{{Operation: "align", Inputs: []DomainValue{{"state", TypeExternalState}, {"alignment", TypeAlignment}}, Outputs: []DomainValue{{"obs", TypeObservation}}}, {Operation: "traverse", Inputs: []DomainValue{{"state", TypeExternalState}, {"path", TypePath}}, Outputs: []DomainValue{{"seq", TypeSymbolSequence}}}, {Operation: "compose", Inputs: []DomainValue{{"seq", TypeSymbolSequence}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			StateSchema:           "12 offsets modulo 23",
			InputSchema:           "SymbolSequence",
			Initialization:        "profile-frozen Latin23/R12 encoding",
			TransitionRules:       []string{"one symbol per ring", "inner-to-outer order"},
			ObservationRule:       "serialize visible letters at the marked radius in physical ring order",
			Serialization:         ObservableContract{SymbolSource: "visible letters at marked radius", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalExactWithConvention, SupportsContext: true, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage, CarrierConvention}, Retrieve: []Carrier{CarrierExternalState, CarrierConvention, CarrierContext}},
			ExpectedReversibility: "exact with profile convention",
			AmbiguitySemantics:    "same as invariant core but under frozen profile values",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption, ErrorConventionCorrupt},
			Parameters:            []ParameterSet{f01ProfileParams},
			SurfaceRole:           SurfaceLiteralSequence,
			runtime:               kindF01,
		},
		{
			ID:                    "f08_serpens_core",
			Version:               "v1",
			Family:                FamilyF08,
			Status:                StatusFExact,
			Provenance:            []string{"FONTANA_MODELS_FROZEN_V1", "FONTANA_OPERATION_ALGEBRA_V1"},
			SourceModels:          []string{"F08_SERPENS_CORE"},
			Encoding:              []OperationInvocation{{Operation: "place", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}, {"symbol", TypeSymbol}}, Outputs: []DomainValue{{"state", TypeExternalState}}, Note: "iterated across the declared path"}},
			Retrieval:             []OperationInvocation{{Operation: "traverse", Inputs: []DomainValue{{"state", TypeExternalState}, {"path", TypePath}}, Outputs: []DomainValue{{"seq", TypeSymbolSequence}}}, {Operation: "compose", Inputs: []DomainValue{{"seq", TypeSymbolSequence}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			StateSchema:           "ordered nullable symbols",
			InputSchema:           "SymbolSequence",
			Initialization:        "empty positional grid",
			TransitionRules:       []string{"path is declared separately from state", "message length remains convention, not hidden metadata"},
			ObservationRule:       "serialize visible symbols by physical position only",
			Serialization:         ObservableContract{SymbolSource: "physical slot contents", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalExactWithConvention, SupportsContext: true, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage, CarrierGeometry, CarrierConvention}, Retrieve: []Carrier{CarrierExternalState, CarrierGeometry, CarrierConvention, CarrierContext}},
			ExpectedReversibility: "exact on declared path only",
			AmbiguitySemantics:    "unknown path or length yields finite traversal candidates",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption, ErrorBoundaryCorruption, ErrorConventionCorrupt},
			Parameters:            []ParameterSet{f08Params},
			SurfaceRole:           SurfaceLiteralSequence,
			runtime:               kindF08,
		},
		{
			ID:                    "f11_arismetricum_core",
			Version:               "v1",
			Family:                FamilyF11,
			Status:                StatusFExact,
			Provenance:            []string{"FONTANA_MODELS_FROZEN_V1", "FONTANA_OPERATION_ALGEBRA_V1"},
			SourceModels:          []string{"F11_ARISMETRICUM_CORE"},
			Encoding:              []OperationInvocation{{Operation: "place", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}, {"symbol", TypeSymbol}}, Outputs: []DomainValue{{"state", TypeExternalState}}, Note: "opaque cue placement"}},
			Retrieval:             []OperationInvocation{{Operation: "index", Inputs: []DomainValue{{"index", TypeIndex}, {"state", TypeExternalState}}, Outputs: []DomainValue{{"position", TypePosition}}}, {Operation: "select", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}}, Outputs: []DomainValue{{"cue_symbol", TypeSymbol}}, Note: "Symbol carrier is interpreted as opaque cue identifier"}},
			StateSchema:           "finite partial map from index to opaque cue",
			InputSchema:           "cue-addressable item set",
			Initialization:        "empty indexed lookup surface",
			TransitionRules:       []string{"index resolves address only", "cue meaning remains outside external state"},
			ObservationRule:       "serialize occupied slots as visible cue-bearing cells",
			Serialization:         ObservableContract{SymbolSource: "sorted visible cue cells", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalCueOnly, SupportsContext: true, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage}, Retrieve: []Carrier{CarrierExternalState, CarrierConvention, CarrierContext}},
			ExpectedReversibility: "cue-only unless an explicit cue convention is supplied",
			AmbiguitySemantics:    "one cue may map to multiple retrieved items until convention/context narrows it",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption, ErrorConventionCorrupt},
			Parameters:            []ParameterSet{f11Params},
			SurfaceRole:           SurfaceOpaqueCue,
			runtime:               kindF11,
		},
		{
			ID:                    "f12_horalogius_core",
			Version:               "v1",
			Family:                FamilyF12,
			Status:                StatusFExact,
			Provenance:            []string{"FONTANA_MODELS_FROZEN_V1", "FONTANA_OPERATION_ALGEBRA_V1"},
			SourceModels:          []string{"F12_HORALOGIUS_CORE"},
			Encoding:              []OperationInvocation{{Operation: "repeat", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "repeat", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}}, Outputs: []DomainValue{{"state", TypeExternalState}}}, {Operation: "signal", Inputs: []DomainValue{{"state", TypeExternalState}}, Outputs: []DomainValue{{"cue", TypeCue}}}, {Operation: "associate", Inputs: []DomainValue{{"cue", TypeCue}, {"memory", TypeInternalMemoryState}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			StateSchema:           "cyclic tick and cue schedule",
			InputSchema:           "cue-addressable item set",
			Initialization:        "cyclic temporal state at a declared initial tick",
			TransitionRules:       []string{"advance by fixed steps", "signal only emitted at configured ticks"},
			ObservationRule:       "serialize emitted cue identifiers only",
			Serialization:         ObservableContract{SymbolSource: "emitted cues", TokenBoundary: BoundaryGenerated, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalCueOnly, SupportsContext: true, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage}, Retrieve: []Carrier{CarrierExternalState, CarrierInternal, CarrierContext}},
			ExpectedReversibility: "cue-only without learned internal association",
			AmbiguitySemantics:    "one cue may keep multiple candidate associations until context narrows them",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption, ErrorConventionCorrupt},
			Parameters:            []ParameterSet{f12Params},
			SurfaceRole:           SurfaceOpaqueCue,
			runtime:               kindF12,
		},
		{
			ID:                    "m_restricted_rotation_index",
			Version:               "v1",
			Family:                FamilyRestrictedRotation,
			Status:                StatusMRestricted,
			Provenance:            []string{"counterfactual_index_after_rotation"},
			SourceModels:          nil,
			Encoding:              []OperationInvocation{{Operation: "rotate", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}, {"orientation", TypeOrientation}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "index", Inputs: []DomainValue{{"index", TypeIndex}, {"state", TypeExternalState}}, Outputs: []DomainValue{{"position", TypePosition}}}, {Operation: "select", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}}, Outputs: []DomainValue{{"cue_symbol", TypeSymbol}}, Note: "type-valid unattested boundary case"}},
			StateSchema:           "rotated indexed cue ring",
			InputSchema:           "cue-addressable item set",
			Initialization:        "opaque cues on a cyclic indexed carrier",
			TransitionRules:       []string{"rotation reorders visible cue positions", "index resolves into rotated topology"},
			ObservationRule:       "serialize rotated cue ring",
			Serialization:         ObservableContract{SymbolSource: "rotated visible cues", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalCueOnly, SupportsContext: true, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage}, Retrieve: []Carrier{CarrierExternalState, CarrierConvention, CarrierContext}},
			ExpectedReversibility: "not a Fontana claim; cue meaning remains external",
			AmbiguitySemantics:    "same cue-to-item ambiguity semantics as indexed cue models",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption, ErrorConventionCorrupt},
			Parameters:            []ParameterSet{rotationParams},
			SurfaceRole:           SurfaceOpaqueCue,
			runtime:               kindRotationIndex,
		},
		{
			ID:                    "m_restricted_storage_associate",
			Version:               "v1.1",
			Family:                FamilyRestrictedAssociation,
			Status:                StatusMRestricted,
			Provenance:            []string{"counterfactual_association_on_literal_store"},
			SourceModels:          nil,
			Encoding:              []OperationInvocation{{Operation: "place", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}, {"symbol", TypeSymbol}}, Outputs: []DomainValue{{"state", TypeExternalState}}, Note: "cue identifiers stored explicitly"}},
			Retrieval:             []OperationInvocation{{Operation: "select", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}}, Outputs: []DomainValue{{"cue_symbol", TypeSymbol}}, Note: "select yields an opaque Symbol identifier"}, {Operation: "associate", Inputs: []DomainValue{{"cue", TypeCue}, {"memory", TypeInternalMemoryState}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			CueConversions:        []CueConversion{{InputName: "cue_symbol", OutputName: "cue", From: TypeSymbol, To: TypeCue, Rule: "OPAQUE_IDENTIFIER: identity representation-level cue interpretation; no state or information effect"}},
			StateSchema:           "explicit positional storage of cue identifiers",
			InputSchema:           "cue-addressable item set",
			Initialization:        "empty explicit storage array",
			TransitionRules:       []string{"opaque cue identifiers are visible", "retrieval still requires internal association"},
			ObservationRule:       "serialize stored cue identifiers by physical position",
			Serialization:         ObservableContract{SymbolSource: "stored cue identifiers", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalCueOnly, SupportsContext: true, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage}, Retrieve: []Carrier{CarrierExternalState, CarrierInternal, CarrierContext}},
			ExpectedReversibility: "cue-only without internal association",
			AmbiguitySemantics:    "same cue may retain multiple candidate intentions",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption, ErrorConventionCorrupt},
			Parameters:            []ParameterSet{storageParams},
			SurfaceRole:           SurfaceOpaqueCue,
			runtime:               kindStorageAssociate,
		},
		{
			ID:                    "synthetic_literal_storage",
			Version:               "v1",
			Family:                FamilyGenericLiteral,
			Status:                StatusGenericControl,
			Provenance:            []string{"synthetic_literal_storage"},
			Encoding:              []OperationInvocation{{Operation: "place", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}, {"symbol", TypeSymbol}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "traverse", Inputs: []DomainValue{{"state", TypeExternalState}, {"path", TypePath}}, Outputs: []DomainValue{{"seq", TypeSymbolSequence}}}, {Operation: "compose", Inputs: []DomainValue{{"seq", TypeSymbolSequence}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			StateSchema:           "synthetic positional literal store",
			InputSchema:           "SymbolSequence",
			Initialization:        "empty synthetic store",
			TransitionRules:       []string{"literal storage control"},
			ObservationRule:       "serialize physical slot contents",
			Serialization:         ObservableContract{SymbolSource: "synthetic slot contents", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalExactWithConvention, SupportsContext: false, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage, CarrierGeometry, CarrierConvention}, Retrieve: []Carrier{CarrierExternalState, CarrierGeometry, CarrierConvention}},
			ExpectedReversibility: "exact literal control",
			AmbiguitySemantics:    "same as simple positional traversal",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption},
			Parameters:            []ParameterSet{f08Params},
			SurfaceRole:           SurfaceLiteralSequence,
			EquivalentTo:          "f08_serpens_core",
			runtime:               kindF08,
		},
		{
			ID:                    "synthetic_cyclic_state",
			Version:               "v1",
			Family:                FamilyGenericCyclic,
			Status:                StatusGenericControl,
			Provenance:            []string{"synthetic_cyclic_state"},
			Encoding:              []OperationInvocation{{Operation: "repeat", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "repeat", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}}, Outputs: []DomainValue{{"state", TypeExternalState}}}, {Operation: "signal", Inputs: []DomainValue{{"state", TypeExternalState}}, Outputs: []DomainValue{{"cue", TypeCue}}}},
			StateSchema:           "synthetic periodic cue emitter",
			InputSchema:           "cue-addressable item set",
			Initialization:        "synthetic cue schedule",
			TransitionRules:       []string{"cue emission only"},
			ObservationRule:       "serialize emitted cues",
			Serialization:         ObservableContract{SymbolSource: "emitted cues", TokenBoundary: BoundaryGenerated, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalCueOnly, SupportsContext: false, SupportsAmbiguity: false},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage}, Retrieve: []Carrier{CarrierExternalState}},
			ExpectedReversibility: "cue-only cyclic control",
			AmbiguitySemantics:    "no literal recovery",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption},
			Parameters:            []ParameterSet{f12Params},
			SurfaceRole:           SurfaceOpaqueCue,
			EquivalentTo:          "f12_horalogius_core",
			runtime:               kindF12,
		},
		{
			ID:                    "synthetic_indexed_lookup",
			Version:               "v1",
			Family:                FamilyGenericIndexed,
			Status:                StatusGenericControl,
			Provenance:            []string{"synthetic_indexed_lookup"},
			Encoding:              []OperationInvocation{{Operation: "place", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}, {"symbol", TypeSymbol}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "index", Inputs: []DomainValue{{"index", TypeIndex}, {"state", TypeExternalState}}, Outputs: []DomainValue{{"position", TypePosition}}}, {Operation: "select", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}}, Outputs: []DomainValue{{"cue_symbol", TypeSymbol}}}},
			StateSchema:           "synthetic indexed cue store",
			InputSchema:           "cue-addressable item set",
			Initialization:        "empty indexed cue surface",
			TransitionRules:       []string{"cue meanings remain outside state"},
			ObservationRule:       "serialize indexed cue slots",
			Serialization:         ObservableContract{SymbolSource: "indexed visible cues", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalCueOnly, SupportsContext: true, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage}, Retrieve: []Carrier{CarrierExternalState, CarrierConvention, CarrierContext}},
			ExpectedReversibility: "exact only with explicit cue map",
			AmbiguitySemantics:    "cue ambiguity is observable and measurable",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption, ErrorConventionCorrupt},
			Parameters:            []ParameterSet{f11Params},
			SurfaceRole:           SurfaceOpaqueCue,
			EquivalentTo:          "f11_arismetricum_core",
			runtime:               kindF11,
		},
		{
			ID:                    "synthetic_cue_based",
			Version:               "v1",
			Family:                FamilyGenericCue,
			Status:                StatusGenericControl,
			Provenance:            []string{"synthetic_cue_based"},
			Encoding:              []OperationInvocation{{Operation: "repeat", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "repeat", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}}, Outputs: []DomainValue{{"state", TypeExternalState}}}, {Operation: "signal", Inputs: []DomainValue{{"state", TypeExternalState}}, Outputs: []DomainValue{{"cue", TypeCue}}}, {Operation: "associate", Inputs: []DomainValue{{"cue", TypeCue}, {"memory", TypeInternalMemoryState}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			StateSchema:           "synthetic cue-to-memory control",
			InputSchema:           "cue-addressable item set",
			Initialization:        "synthetic cue schedule",
			TransitionRules:       []string{"cue emission plus association"},
			ObservationRule:       "serialize emitted cues only",
			Serialization:         ObservableContract{SymbolSource: "emitted cues", TokenBoundary: BoundaryGenerated, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalCueOnly, SupportsContext: true, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage}, Retrieve: []Carrier{CarrierExternalState, CarrierInternal, CarrierContext}},
			ExpectedReversibility: "cue-only unless internal memory is supplied",
			AmbiguitySemantics:    "multiple candidate associations remain explicit",
			ErrorSemantics:        []ErrorClass{ErrorStateCorruption, ErrorConventionCorrupt},
			Parameters:            []ParameterSet{f12Params},
			SurfaceRole:           SurfaceOpaqueCue,
			EquivalentTo:          "f12_horalogius_core",
			runtime:               kindF12,
		},
		{
			ID:                    "synthetic_ambiguous",
			Version:               "v1.1",
			Family:                FamilyGenericAmbiguous,
			Status:                StatusGenericControl,
			Provenance:            []string{"synthetic_ambiguous"},
			Encoding:              []OperationInvocation{{Operation: "place", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}, {"symbol", TypeSymbol}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "select", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}}, Outputs: []DomainValue{{"cue_symbol", TypeSymbol}}}, {Operation: "associate", Inputs: []DomainValue{{"cue", TypeCue}, {"memory", TypeInternalMemoryState}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			CueConversions:        []CueConversion{{InputName: "cue_symbol", OutputName: "cue", From: TypeSymbol, To: TypeCue, Rule: "OPAQUE_IDENTIFIER: identity representation-level cue interpretation; no state or information effect"}},
			StateSchema:           "synthetic ambiguous cue storage",
			InputSchema:           "cue-addressable item set",
			Initialization:        "single visible cue can point to multiple candidate items",
			TransitionRules:       []string{"visible state and hidden intention remain separate"},
			ObservationRule:       "serialize visible cue identifiers only",
			Serialization:         ObservableContract{SymbolSource: "visible cues", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalAmbiguous, SupportsContext: true, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage}, Retrieve: []Carrier{CarrierExternalState, CarrierInternal, CarrierContext}},
			ExpectedReversibility: "explicitly many-to-one",
			AmbiguitySemantics:    "ambiguity set is primary output until context narrows it",
			ErrorSemantics:        []ErrorClass{ErrorConventionCorrupt},
			Parameters:            []ParameterSet{storageParams},
			SurfaceRole:           SurfaceOpaqueCue,
			EquivalentTo:          "m_restricted_storage_associate",
			runtime:               kindStorageAssociate,
		},
		{
			ID:                    "negative_randomized_convention",
			Version:               "v1",
			Family:                FamilyNegativeConvention,
			Status:                StatusGenericControl,
			Provenance:            []string{"randomized convention control"},
			SourceModels:          []string{"F01_SPECULUM_CORE"},
			Encoding:              []OperationInvocation{{Operation: "rotate", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}, {"orientation", TypeOrientation}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "align", Inputs: []DomainValue{{"state", TypeExternalState}, {"alignment", TypeAlignment}}, Outputs: []DomainValue{{"obs", TypeObservation}}}, {Operation: "traverse", Inputs: []DomainValue{{"state", TypeExternalState}, {"path", TypePath}}, Outputs: []DomainValue{{"seq", TypeSymbolSequence}}}, {Operation: "compose", Inputs: []DomainValue{{"seq", TypeSymbolSequence}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			StateSchema:           "same F01 state; degraded by wrong convention",
			InputSchema:           "SymbolSequence",
			Initialization:        "same as F01",
			TransitionRules:       []string{"negative control uses wrong convention at retrieval"},
			ObservationRule:       "same visible letters as F01",
			Serialization:         ObservableContract{SymbolSource: "visible letters at marked radius", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalAmbiguous, SupportsContext: false, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage, CarrierConvention}, Retrieve: []Carrier{CarrierExternalState, CarrierConvention}},
			ExpectedReversibility: "should lose exact recovery under wrong convention",
			AmbiguitySemantics:    "wrong convention broadens candidate set",
			ErrorSemantics:        []ErrorClass{ErrorConventionCorrupt},
			Parameters:            []ParameterSet{f01CoreParams},
			SurfaceRole:           SurfaceLiteralSequence,
			EquivalentTo:          "f01_speculum_core",
			runtime:               kindF01,
		},
		{
			ID:                    "negative_randomized_path",
			Version:               "v1",
			Family:                FamilyNegativePath,
			Status:                StatusGenericControl,
			Provenance:            []string{"randomized path control"},
			SourceModels:          []string{"F08_SERPENS_CORE"},
			Encoding:              []OperationInvocation{{Operation: "place", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}, {"symbol", TypeSymbol}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "traverse", Inputs: []DomainValue{{"state", TypeExternalState}, {"path", TypePath}}, Outputs: []DomainValue{{"seq", TypeSymbolSequence}}}, {Operation: "compose", Inputs: []DomainValue{{"seq", TypeSymbolSequence}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			StateSchema:           "same F08 state; retrieval with wrong path knowledge",
			InputSchema:           "SymbolSequence",
			Initialization:        "same as F08",
			TransitionRules:       []string{"negative control removes path knowledge"},
			ObservationRule:       "same visible slots as F08",
			Serialization:         ObservableContract{SymbolSource: "physical slot contents", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalAmbiguous, SupportsContext: false, SupportsAmbiguity: true},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage, CarrierGeometry, CarrierConvention}, Retrieve: []Carrier{CarrierExternalState, CarrierGeometry, CarrierConvention}},
			ExpectedReversibility: "should lose exact recovery without path knowledge",
			AmbiguitySemantics:    "compatible traversals stay explicit",
			ErrorSemantics:        []ErrorClass{ErrorBoundaryCorruption},
			Parameters:            []ParameterSet{f08Params},
			SurfaceRole:           SurfaceLiteralSequence,
			EquivalentTo:          "f08_serpens_core",
			runtime:               kindF08,
		},
		{
			ID:                    "negative_randomized_cue_association",
			Version:               "v1",
			Family:                FamilyNegativeCueAssociation,
			Status:                StatusGenericControl,
			Provenance:            []string{"randomized cue association control"},
			SourceModels:          []string{"F12_HORALOGIUS_CORE"},
			Encoding:              []OperationInvocation{{Operation: "repeat", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "repeat", Inputs: []DomainValue{{"state", TypeExternalState}, {"step", TypeStep}}, Outputs: []DomainValue{{"state", TypeExternalState}}}, {Operation: "signal", Inputs: []DomainValue{{"state", TypeExternalState}}, Outputs: []DomainValue{{"cue", TypeCue}}}, {Operation: "associate", Inputs: []DomainValue{{"cue", TypeCue}, {"memory", TypeInternalMemoryState}}, Outputs: []DomainValue{{"item", TypeRetrievedItem}}}},
			StateSchema:           "same F12 state; degraded by wrong association map",
			InputSchema:           "cue-addressable item set",
			Initialization:        "same as F12",
			TransitionRules:       []string{"negative control supplies wrong memory mapping"},
			ObservationRule:       "same emitted cue as F12",
			Serialization:         ObservableContract{SymbolSource: "emitted cues", TokenBoundary: BoundaryGenerated, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalCueOnly, SupportsContext: false, SupportsAmbiguity: false},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage}, Retrieve: []Carrier{CarrierExternalState, CarrierInternal}},
			ExpectedReversibility: "wrong association should not recover the intended item",
			AmbiguitySemantics:    "unlearned cue remains cue-only",
			ErrorSemantics:        []ErrorClass{ErrorConventionCorrupt},
			Parameters:            []ParameterSet{f12Params},
			SurfaceRole:           SurfaceOpaqueCue,
			EquivalentTo:          "f12_horalogius_core",
			runtime:               kindF12,
		},
		{
			ID:                    "negative_randomized_index_mapping",
			Version:               "v1",
			Family:                FamilyNegativeIndexMapping,
			Status:                StatusGenericControl,
			Provenance:            []string{"randomized index mapping control"},
			SourceModels:          []string{"F11_ARISMETRICUM_CORE"},
			Encoding:              []OperationInvocation{{Operation: "place", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}, {"symbol", TypeSymbol}}, Outputs: []DomainValue{{"state", TypeExternalState}}}},
			Retrieval:             []OperationInvocation{{Operation: "index", Inputs: []DomainValue{{"index", TypeIndex}, {"state", TypeExternalState}}, Outputs: []DomainValue{{"position", TypePosition}}}, {Operation: "select", Inputs: []DomainValue{{"state", TypeExternalState}, {"position", TypePosition}}, Outputs: []DomainValue{{"cue_symbol", TypeSymbol}}}},
			StateSchema:           "same F11 state; degraded by wrong cue mapping",
			InputSchema:           "cue-addressable item set",
			Initialization:        "same as F11",
			TransitionRules:       []string{"negative control supplies non-matching cue map"},
			ObservationRule:       "same visible cue slots as F11",
			Serialization:         ObservableContract{SymbolSource: "sorted visible cue cells", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryGenerated, ExcludesHiddenState: true},
			RetrievalRelation:     RetrievalRelation{Kind: RetrievalCueOnly, SupportsContext: false, SupportsAmbiguity: false},
			Carriers:              CarrierRequirements{Encode: []Carrier{CarrierMessage}, Retrieve: []Carrier{CarrierExternalState, CarrierConvention}},
			ExpectedReversibility: "wrong cue mapping should not recover intended item",
			AmbiguitySemantics:    "falls back to cue-only",
			ErrorSemantics:        []ErrorClass{ErrorConventionCorrupt},
			Parameters:            []ParameterSet{f11Params},
			SurfaceRole:           SurfaceOpaqueCue,
			EquivalentTo:          "f11_arismetricum_core",
			runtime:               kindF11,
		},
	}
}

func InvalidControls() []MechanismSpec {
	return []MechanismSpec{{
		ID:                "synthetic_invalid_signal",
		Version:           "v1",
		Family:            FamilyGenericCue,
		Status:            StatusForbidden,
		Provenance:        []string{"synthetic_invalid_signal"},
		Encoding:          nil,
		Retrieval:         []OperationInvocation{{Operation: "signal", Inputs: nil, Outputs: []DomainValue{{"cue", TypeCue}}}},
		StateSchema:       "none",
		InputSchema:       "none",
		Serialization:     ObservableContract{SymbolSource: "none", TokenBoundary: BoundaryNotDefined, LineBoundary: BoundaryNotDefined, UnitBoundary: BoundaryNotDefined, ExcludesHiddenState: true},
		RetrievalRelation: RetrievalRelation{Kind: RetrievalCueOnly},
		Carriers:          CarrierRequirements{Retrieve: []Carrier{CarrierExternalState}},
		Parameters:        []ParameterSet{{ID: "invalid", Origin: OriginControlOnly, Frozen: true}},
		SurfaceRole:       SurfaceOpaqueCue,
		runtime:           kindUnknown,
	}}
}
