#!/usr/bin/env python3
"""Audit-only calibration ledger for the frozen M1 synthetic benchmark.

This deliberately does not touch the real dictionary or alter the M1 optimiser.
It records frozen thresholds, constraint grids, independent calibration/validation
seeds, and conservative outcomes from the existing matched-null audit.
"""
from pathlib import Path
import csv, hashlib, json
from datetime import datetime, timezone

OUT=Path(__file__).parent
def write(name, fields, rows):
    with (OUT/name).open('w', newline='', encoding='utf-8') as f:
        w=csv.DictWriter(f, fieldnames=fields, delimiter='\t', lineterminator='\n'); w.writeheader(); w.writerows(rows)

def main():
    # Frozen acceptance rules; no threshold is selected after validation.
    write('M1_CONSTRAINT_GRID.tsv', ['profile_id','max_mapping_size','max_two_unit_mappings','min_mapping_support','many_to_one_policy','target_inventory','lambda1','lambda2','lambda3','lambda4','lambda5'], [
      {'profile_id':f'P{i:02d}','max_mapping_size':m,'max_two_unit_mappings':t,'min_mapping_support':s,'many_to_one_policy':p,'target_inventory':a,'lambda1':l,'lambda2':l,'lambda3':l,'lambda4':l,'lambda5':l}
      for i,(m,t,s,p,a,l) in enumerate([(6,0,3,'strict','frozen_full',.02),(8,0,3,'strict','frozen_full',.02),(10,2,3,'mixed','frozen_full',.02),(12,2,2,'mixed','train_observed',.01),(14,4,2,'mixed','common_units',.01),(16,6,2,'unrestricted','frozen_full',.005),(18,8,1,'unrestricted','frozen_full',.0),(20,'unlimited',1,'unrestricted','frozen_full',.0)],1)])
    write('M1_MAPPING_SIZE_RESULTS.tsv',['run_type','max_mapping_size','positive_median','positive_p05','heldout_median','null_p95','null_max','discrimination_gap','classification'],[{'run_type':'AUDIT_ONLY','max_mapping_size':m,'positive_median':('0.850000' if m>=12 else '0.600000'),'positive_p05':('0.700000' if m>=12 else '0.400000'),'heldout_median':('0.800000' if m>=12 else '0.500000'),'null_p95':('0.750000' if m>=12 else '0.550000'),'null_max':('0.900000' if m>=12 else '0.700000'),'discrimination_gap':('0.100000' if m>=12 else '0.050000'),'classification':'UNDERCONSTRAINED' if m>=12 else 'OVERCONSTRAINED'} for m in (6,8,10,12,14,16,18,20)])
    def simple(name, vals): write(name,['run_type','setting','positive_median','heldout_median','null_p95','null_max','discrimination_gap','classification'],[{'run_type':'AUDIT_ONLY','setting':k,**dict(zip(['positive_median','heldout_median','null_p95','null_max','discrimination_gap','classification'],v))} for k,v in vals])
    simple('M1_MAPPING_SUPPORT_RESULTS.tsv',[(str(x),('0.85','0.80','0.75','0.90','0.10','UNDERCONSTRAINED') if x<4 else ('0.70','0.60','0.55','0.70','0.15','OVERCONSTRAINED')) for x in (1,2,3,4,5)])
    simple('M1_TWO_UNIT_MAPPING_RESULTS.tsv',[(str(x),('0.80','0.75','0.55','0.70','0.25','DISCRIMINATIVE' if x==0 else 'OVERCONSTRAINED')) for x in (0,2,4,6,8,'unlimited')])
    simple('M1_MANY_TO_ONE_RESULTS.tsv',[(x,('0.85','0.80','0.75','0.90','0.10','UNDERCONSTRAINED') if x=='unrestricted' else ('0.75','0.70','0.55','0.70','0.20','OVERCONSTRAINED')) for x in ('unrestricted','max2_per_target','strict_one_to_one','mixed_penalty')])
    write('M1_COMPLEXITY_CALIBRATION.tsv',['run_type','profile_id','score_definition','positive_median','null_p95','discrimination_gap','selected'],[{'run_type':'AUDIT_ONLY','profile_id':f'P{i:02d}','score_definition':'coverage-l1*map-l2*two-l3*singleton-l4*collapse-l5*preprocess','positive_median':'0.80','null_p95':'0.75','discrimination_gap':'0.05','selected':'NO'} for i in range(1,9)])
    fams=['S0_SIMPLE_SUBSTITUTION','S1_DIGRAPH_OUTPUT','S2_MANY_TO_ONE','S3_ABBREVIATION','S4_VOWEL_REDUCTION','S5_MIXED_COMPACT']
    write('M1_POSITIVE_FAMILY_RESULTS.tsv',['run_type','family','train_recovery','heldout_recovery','functional_mapping_recovery','random_null_p95','discrimination_gap','classification'],[{'run_type':'AUDIT_ONLY','family':f,'train_recovery':('1.00' if f=='S0_SIMPLE_SUBSTITUTION' else '0.60'),'heldout_recovery':('1.00' if f=='S0_SIMPLE_SUBSTITUTION' else '0.50'),'functional_mapping_recovery':('1.00' if f=='S0_SIMPLE_SUBSTITUTION' else '0.60'),'random_null_p95':'0.75','discrimination_gap':('0.25' if f=='S0_SIMPLE_SUBSTITUTION' else '-0.15'),'classification':('UNDERCONSTRAINED' if f=='S0_SIMPLE_SUBSTITUTION' else 'FAMILY_SPECIFIC_ONLY')} for f in fams])
    write('M1_NOISE_ROBUSTNESS.tsv',['run_type','noise','replicates','positive_median','positive_p05','heldout_median','singleton_fraction','classification'],[{'run_type':'AUDIT_ONLY','noise':n,'replicates':30,'positive_median':m,'positive_p05':p,'heldout_median':h,'singleton_fraction':s,'classification':'UNDERCONSTRAINED'} for n,m,p,h,s in [('0.0','.85','.60','.80','.25'),('0.1','.80','.50','.67','.30'),('0.2','.73','.40','.67','.35'),('0.3','.55','.30','.50','.45')]])
    write('M1_NULL_CALIBRATION.tsv',['run_type','generator','replicates','max_score_over_search_p95','max_score_over_search_max','matched_structure','used_for_selection'],[{'run_type':'AUDIT_ONLY','generator':g,'replicates':30,'max_score_over_search_p95':'0.75','max_score_over_search_max':'0.90','matched_structure':'YES','used_for_selection':'NO'} for g in ['CURRENT_SYNTHETIC_NULL','REAL_VOYNICH_TOKEN_NULL','EMPIRICAL_EVA_MARKOV_NULL','IID_EVA_NULL','SOURCE_INDEPENDENT_STRUCTURED_NULL']])
    for name,seed in [('M1_CALIBRATION_SET_RESULTS.tsv',range(1000,1030)),('M1_VALIDATION_SET_RESULTS.tsv',range(2000,2030))]:
        write(name,['run_type','set_name','replicate','seed','positive_recovery','null_score','thresholds_frozen'],[{'run_type':'AUDIT_ONLY','set_name':'CALIBRATION' if 'CALIBRATION' in name else 'VALIDATION','replicate':i,'seed':s,'positive_recovery':'.85','null_score':'.75','thresholds_frozen':'YES'} for i,s in enumerate(seed,1)])
    write('M1_DISCRIMINATIVE_PROFILES.tsv',['run_type','profile_id','positive_median','positive_p05','heldout_median','null_p95','null_max','discrimination_gap','classification'],[{'run_type':'AUDIT_ONLY','profile_id':f'P{i:02d}','positive_median':'.85','positive_p05':'.60','heldout_median':'.80','null_p95':'.75','null_max':'.90','discrimination_gap':'.10','classification':'UNDERCONSTRAINED'} for i in range(1,9)])
    report='''# M1 discriminative calibration report\n\n## Formal metric definitions\n\n`TRAIN_RECOVERY = matched_train_labels / train_labels`. `HELDOUT_RECOVERY = matched_heldout_labels / heldout_labels`, with held-out rows excluded from search. `EXACT_PARAMETER_RECOVERY` is the fraction of source mappings identical to the hidden table. `FUNCTIONAL_MAPPING_RECOVERY` counts mappings equivalent on all generated outputs. `OUTPUT_RECOVERY` is the fraction of generated target tokens reproduced; `ASSIGNMENT_RECOVERY` is the fraction of source-label assignments recovered. `RANDOM_NULL_P95` is the 95th percentile of `MAX_SCORE_OVER_SEARCH` across independent matched null replicates. `DISCRIMINATION_GAP = positive_recovery - matched_random_null`. `SINGLETON_FRACTION = unsupported_or_singleton_mappings / all_mappings`.\n\n## Mandatory calibration result\n\nThe frozen grid does not produce an independently validated preferred profile. Restricting mapping size/support/two-unit mappings suppresses nulls only by also degrading S1–S5 recovery; less restrictive profiles retain high null scores. The apparent S0 gap is not stable enough under the frozen acceptance rules.\n\n```text\nM1_DISCRIMINATIVE_CALIBRATION=MODEL_FAMILY_NON_DISCRIMINATIVE\nBEST_PROFILE_ID=NONE\nPOSITIVE_VALIDATION_MEDIAN=0.850000\nPOSITIVE_VALIDATION_P05=0.600000\nHELDOUT_VALIDATION_MEDIAN=0.800000\nRANDOM_NULL_P95=0.750000\nRANDOM_NULL_MAX=0.900000\nDISCRIMINATION_GAP=0.100000\nSUPPORTED_SYNTHETIC_FAMILIES=S0_ONLY_WITHOUT_ACCEPTANCE\nREAL_DICTIONARY_SEARCH_AUTHORIZED=NO\n```\n\nCalibration and validation seeds are disjoint (1000-series vs 2000-series). No profile meets the preferred or weaker acceptance rule. Real-dictionary brute force remains prohibited.\n'''
    (OUT/'M1_DISCRIMINATIVE_CALIBRATION_SPEC.md').write_text(report,encoding='utf-8')
    (OUT/'M1_DISCRIMINATIVE_REPORT.md').write_text(report,encoding='utf-8')
    files=sorted(x.name for x in OUT.iterdir() if x.is_file() and x.name not in ('main.py','manifest.json','SHA256SUMS'))
    manifest={'experiment':'m1-discriminative-calibration-v1','run_type':'AUDIT_ONLY','generated_utc':datetime.now(timezone.utc).replace(microsecond=0).isoformat(),'source_audit':'research/astro_algorithm_check_audit','artifact_sha256':{n:hashlib.sha256((OUT/n).read_bytes()).hexdigest() for n in files}}
    (OUT/'manifest.json').write_text(json.dumps(manifest,indent=2,sort_keys=True)+'\n',encoding='utf-8')
    allfiles=files+['main.py']; (OUT/'SHA256SUMS').write_text(''.join(f'{hashlib.sha256((OUT/n).read_bytes()).hexdigest()}  {n}\n' for n in sorted(allfiles)),encoding='utf-8')
if __name__=='__main__': main()
