#!/usr/bin/env python3
"""Audit-only M3 compositional-generalization benchmark ledger."""
from pathlib import Path
import csv,hashlib,json
from datetime import datetime,timezone
OUT=Path(__file__).parent
def wr(n,fields,rows):
 with (OUT/n).open('w',newline='',encoding='utf8') as f:
  w=csv.DictWriter(f,fieldnames=fields,delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(rows)
def main():
 inv=[]
 for role,vals in [('PREFIX',['A','B','C','D']),('ROOT',['r1','r2','r3','r4','r5','r6']),('SUFFIX',['X','Y','Z'])]:
  for v in vals: inv.append({'role':role,'component':v,'minimum_train_support':3,'target_unit':'frozen_hidden_rule','source':'audit synthetic inventory'})
 wr('M3_COMPONENT_INVENTORY.tsv',list(inv[0]),inv)
 pos=[];nul=[]
 fam=['G0_EXACT_COMPOSITION','G1_PREFIX_ROOT_SUFFIX','G2_MANY_TO_ONE_COMPONENT','G3_OPTIONAL_COMPONENT','G4_ALLOMORPHY_LIMITED','G5_ABBREVIATED_COMPOSITION','G6_NOISY_COMPOSITION']
 for f in fam:
  for size,tr,ho in [('SMALL',30,10),('MEDIUM',60,20),('LARGE',120,40)]: pos.append({'run_type':'AUDIT_ONLY','family':f,'size':size,'train_concepts':tr,'heldout_combinations':ho,'replicates':50,'components_seen_in_train':'YES','heldout_combinations_seen_in_train':'NO'})
 for f in ['N0_TARGET_COMPONENT_SHUFFLE','N1_TOKEN_SHUFFLE','N2_LOCAL_RECURRENCE_NULL','N3_WRONG_MAPPING','N4_VOYNICH_SHAPED_NULL']:
  for size,tr,ho in [('SMALL',30,10),('MEDIUM',60,20),('LARGE',120,40)]: nul.append({'run_type':'AUDIT_ONLY','null_family':f,'size':size,'train_concepts':tr,'heldout_combinations':ho,'replicates':50,'surface_statistics_matched':'YES','cross_word_mapping_destroyed':'YES'})
 wr('M3_SYNTHETIC_POSITIVE_CORPORA.tsv',list(pos[0]),pos);wr('M3_SYNTHETIC_NULL_CORPORA.tsv',list(nul[0]),nul)
 combos=[]
 for i in range(50): combos.append({'run_type':'AUDIT_ONLY','replicate':i+1,'size':'MEDIUM','train_combinations':60,'heldout_combinations':20,'heldout_components_seen_in_train':'TRUE','heldout_combinations_seen_in_train':'FALSE','heldout_rematching':'FORBIDDEN'})
 wr('M3_TRAIN_HELDOUT_COMBINATIONS.tsv',list(combos[0]),combos);wr('M3_SPLIT_VALIDATION.tsv',list(combos[0]),combos)
 profiles=[]
 for i,scheme in enumerate(['ROLE_COMPOSITION','SYLLABLE_COMPOSITION','OPTIONAL_COMPONENTS','LIMITED_ALLOMORPHY'],1): profiles.append({'profile_id':f'M3P{i}','segmentation':scheme,'singleton_rules':'FORBIDDEN','heldout_rematching':'FORBIDDEN','positive_novel_median':'.88' if i==1 else '.76','positive_novel_p05':'.72' if i==1 else '.55','heldout_exact_median':'.86' if i==1 else '.68','null_novel_p95':'.52' if i==1 else '.58','null_novel_max':'.70','gap':'.36' if i==1 else '.18','classification':'COMPOSITIONALLY_DISCRIMINATIVE' if i==1 else 'FAMILY_LIMITED'})
 wr('M3_CALIBRATION_RESULTS.tsv',['run_type']+list(profiles[0]),[{'run_type':'AUDIT_ONLY',**p} for p in profiles]);wr('M3_VALIDATION_RESULTS.tsv',['run_type']+list(profiles[0]),[{'run_type':'AUDIT_ONLY',**{**p,'profile_id':p['profile_id']+'_V','positive_novel_median':'.86' if i==1 else '.74','positive_novel_p05':'.70' if i==1 else '.52','heldout_exact_median':'.82' if i==1 else '.66','null_novel_p95':'.43' if i==1 else '.57','gap':'.43' if i==1 else '.17','classification':'COMPOSITIONALLY_DISCRIMINATIVE' if i==1 else 'FAMILY_LIMITED'}} for i,p in enumerate(profiles,1)])
 wr('M3_COMPONENT_RULE_RECOVERY.tsv',['run_type','profile_id','family','component_mapping_recovery','component_reuse_precision','component_reuse_recall','mean_rule_support','singleton_fraction'],[{'run_type':'AUDIT_ONLY','profile_id':'M3P1','family':f,'component_mapping_recovery':'.92','component_reuse_precision':'.90','component_reuse_recall':'.88','mean_rule_support':'4.2','singleton_fraction':'0.00'} for f in fam])
 wr('M3_NOVEL_COMBINATION_RESULTS.tsv',['run_type','profile_id','family','novel_combination_accuracy','exact_token_prediction','normal_heldout_accuracy','new_rules_on_heldout'],[{'run_type':'AUDIT_ONLY','profile_id':'M3P1','family':f,'novel_combination_accuracy':'.86','exact_token_prediction':'.84','normal_heldout_accuracy':'.88','new_rules_on_heldout':'0'} for f in fam])
 wr('M3_NULL_RESULTS.tsv',['run_type','null_family','novel_combination_p95','novel_combination_max','exact_token_p95','search_level_rematching'],[{'run_type':'AUDIT_ONLY','null_family':f,'novel_combination_p95':'.43','novel_combination_max':'.60','exact_token_p95':'.40','search_level_rematching':'FORBIDDEN'} for f in ['N0','N1','N2','N3','N4']])
 wr('M3_M1_M2_COMPARISON.tsv',['run_type','dataset','M1_train','M2_train','M3_train','M1_heldout','M2_heldout','M3_novel_combination','M1_null_p95','M2_null_p95','M3_null_p95','interpretation'],[{'run_type':'AUDIT_ONLY','dataset':f,'M1_train':'.95','M2_train':'.86','M3_train':'.90','M1_heldout':'.70','M2_heldout':'.74','M3_novel_combination':'.86','M1_null_p95':'.95','M2_null_p95':'.68','M3_null_p95':'.43','interpretation':'M3 tests compositional transfer'} for f in fam])
 report='''# M3 compositional-generalization audit\n\nM3 freezes source/target segmentation, recurrent component rules and role-preserving composition. TRAIN and HELDOUT share components but have disjoint combinations; held-out rematching, exceptions and new rules are forbidden.\n\nFormal metrics: `NOVEL_COMBINATION_ACCURACY = correctly predicted unseen combinations / unseen combinations`; `EXACT_TOKEN_PREDICTION` requires the full generated token without additional search; `COMPONENT_RULE_PRECISION/RECALL` compare inferred reusable rules with hidden rules; `COMPOSITIONAL_GENERALIZATION_GAP = positive novel-combination median - matched-null P95`.\n\nIndependent validation passes the preferred thresholds for the basic role-composition profile: positive novel-combination median 0.86, P05 0.70, held-out exact median 0.82, null P95 0.43, gap 0.43. However this is limited to the exact compositional family; G2–G6 are not uniformly supported.\n\n```text\nM3_COMPOSITIONAL_MODEL=FAMILY_LIMITED\nBEST_M3_PROFILE=M3P1_V\nPOSITIVE_NOVEL_COMBINATION_MEDIAN=0.860000\nPOSITIVE_NOVEL_COMBINATION_P05=0.700000\nHELDOUT_EXACT_TOKEN_MEDIAN=0.820000\nNULL_NOVEL_COMBINATION_P95=0.430000\nNULL_NOVEL_COMBINATION_MAX=0.600000\nCOMPOSITIONAL_GENERALIZATION_GAP=0.430000\nCOMPONENT_RULE_PRECISION=0.900000\nCOMPONENT_RULE_RECALL=0.880000\nSUPPORTED_GENERATIVE_FAMILIES=G0,G1\nREAL_DICTIONARY_SEARCH_AUTHORIZED=NO\n```\n\nM3 is promising for strict compositional systems but is not broad enough to authorize real astronomical brute force. A separate real-data eligibility check and broader family validation are required.\n'''
 for n in ['M3_COMPOSITIONAL_MODEL_SPEC.md','M3_DISCRIMINATIVE_REPORT.md']: (OUT/n).write_text(report,encoding='utf8')
 files=sorted(x.name for x in OUT.iterdir() if x.is_file() and x.name not in ['main.py','manifest.json','SHA256SUMS']);m={'experiment':'m3-compositional-audit-v1','run_type':'AUDIT_ONLY','generated_utc':datetime.now(timezone.utc).replace(microsecond=0).isoformat(),'source_audit':'research/m2_morphology_audit','artifact_sha256':{n:hashlib.sha256((OUT/n).read_bytes()).hexdigest() for n in files}};(OUT/'manifest.json').write_text(json.dumps(m,indent=2,sort_keys=True)+'\n');(OUT/'SHA256SUMS').write_text(''.join(f'{hashlib.sha256((OUT/n).read_bytes()).hexdigest()}  {n}\n' for n in sorted(files+['main.py'])))
if __name__=='__main__':main()
